#!/usr/bin/env node
import { cp, mkdir, rm } from 'node:fs/promises';

const dist = new URL('../dist/', import.meta.url);
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(new URL('../index.html', import.meta.url), new URL('./index.html', dist));
await cp(new URL('../trackers.html', import.meta.url), new URL('./trackers.html', dist));
await cp(new URL('../playbook.html', import.meta.url), new URL('./playbook.html', dist));
await cp(new URL('../agenda.html', import.meta.url), new URL('./agenda.html', dist));
await cp(new URL('../narratives.html', import.meta.url), new URL('./narratives.html', dist));
await cp(new URL('../evidence.html', import.meta.url), new URL('./evidence.html', dist));
await cp(new URL('../records.html', import.meta.url), new URL('./records.html', dist));
await cp(new URL('../interview.html', import.meta.url), new URL('./interview.html', dist));
await cp(new URL('../tensions.html', import.meta.url), new URL('./tensions.html', dist));
await cp(new URL('../war-room.html', import.meta.url), new URL('./war-room.html', dist));
await cp(new URL('../investigations.html', import.meta.url), new URL('./investigations.html', dist));
await cp(new URL('../radar.html', import.meta.url), new URL('./radar.html', dist));
await cp(new URL('../briefing.html', import.meta.url), new URL('./briefing.html', dist));
await cp(new URL('../coverage.html', import.meta.url), new URL('./coverage.html', dist));
await cp(new URL('../search.html', import.meta.url), new URL('./search.html', dist));
await cp(new URL('../topic.html', import.meta.url), new URL('./topic.html', dist));
await cp(new URL('../notebook.html', import.meta.url), new URL('./notebook.html', dist));
await cp(new URL('../accountability.html', import.meta.url), new URL('./accountability.html', dist));
await cp(new URL('../network.html', import.meta.url), new URL('./network.html', dist));
await cp(new URL('../promises.html', import.meta.url), new URL('./promises.html', dist));
await cp(new URL('../claims.html', import.meta.url), new URL('./claims.html', dist));
await cp(new URL('../timeline.html', import.meta.url), new URL('./timeline.html', dist));
await cp(new URL('../sources.html', import.meta.url), new URL('./sources.html', dist));
await cp(new URL('../metrics.html', import.meta.url), new URL('./metrics.html', dist));
await cp(new URL('../news.html', import.meta.url), new URL('./news.html', dist));
await cp(new URL('../charts.html', import.meta.url), new URL('./charts.html', dist));
await cp(new URL('../src/', import.meta.url), new URL('./src/', dist), { recursive: true });
await cp(new URL('../public/', import.meta.url), dist, { recursive: true });
console.log('Static site built to dist/');
