import { buildChartsPageModel } from './charts-shared.js';
import { loadTrackerPage } from './tracker-loader.js';

const icon = {
  bot: '🤖',
  chart: '📊',
  refresh: '🔄',
};

let trackerData;
let trackerContext;
let defaultCharts = [];
let generatedCharts = [];
let isGenerating = false;
let generationError = '';
let chartRequestText = '';
let hasAutoGeneratedFromUrl = false;
let hasGeneratedPromptCharts = false;

async function boot() {
  trackerContext = await loadTrackerPage('daniel-lurie');
  trackerData = trackerContext.data;
  chartRequestText = readPromptFromUrl();
  defaultCharts = buildChartsPageModel(trackerData);
  generatedCharts = defaultCharts;
  render();
  if (chartRequestText && !hasAutoGeneratedFromUrl) {
    hasAutoGeneratedFromUrl = true;
    await generateCharts();
  }
}

function render() {
  const data = trackerData;
  const isPromptMode = Boolean(chartRequestText && hasAutoGeneratedFromUrl);
  const isCleanPromptView = isPromptMode && readViewModeFromUrl() === 'clean';
  const chartsToRender = (isPromptMode && !hasGeneratedPromptCharts) ? [] : generatedCharts;
  const chartCount = chartsToRender.length;
  const summarySection = `
    <section class="dashboard-grid summary-grid">
      <article class="metric-card"><div class="metric-icon">📈</div><span>Charts live</span><strong>${chartCount}</strong><p>Default views come from tracker data; new charts appear only when requested</p></article>
      <article class="metric-card"><div class="metric-icon">🗄️</div><span>Observed metrics</span><strong>${data.metrics.filter((metric) => metric.observations?.length).length}</strong><p>Available for AI interpretation and chart selection</p></article>
      <article class="metric-card"><div class="metric-icon">🤖</div><span>AI role</span><strong>Specs only</strong><p>AI interprets data and returns fixed-format chart specs, not frontend code</p></article>
    </section>
  `;
  const chartsSection = `
    <section class="section ${isPromptMode ? 'section-priority' : ''}">
      <div class="panel">
        <div class="section-title">
          <div class="section-icon">${icon.chart}</div>
          <div>
            <p>${isPromptMode ? 'Generated from prompt' : 'Charts'}</p>
            <h2>${isPromptMode ? 'Prompt-driven visualization' : 'On-demand visualizations'}</h2>
          </div>
        </div>
        ${isPromptMode ? `<p class="method-note"><strong>Prompt:</strong> ${escapeHtml(chartRequestText)}</p>` : ''}
        <div class="real-chart-grid">
          ${isGenerating && isPromptMode ? '<div class="empty-state">Generating chart view from the prompt and stored tracker data...</div>' : ''}
          ${!isGenerating && chartsToRender.length ? chartsToRender.map(renderGeneratedChart).join('') : ''}
          ${!isGenerating && !chartsToRender.length ? '<div class="empty-state">No chartable tracker data is available yet. Click Generate charts to ask the backend for chart specs from the latest data.</div>' : ''}
        </div>
      </div>
    </section>
  `;

  const root = document.getElementById('root');
  root.className = isCleanPromptView ? 'clean-prompt-view' : '';
  root.innerHTML = `
    <header class="hero ${isCleanPromptView ? 'hero-compact' : ''}">
      <nav>
        <a class="brand" href="${trackerContext.trackerHref('/')}">${icon.bot} Politics Tracker MVP</a>
        <div class="nav-links">
          ${trackerContext.navLinksHtml('/charts.html')}
        </div>
      </nav>
      <div class="hero-content">
        <div>
          <p class="eyebrow">Visual reporting</p>
          <h1>${isPromptMode ? 'Prompt-generated chart view.' : 'Clean chart views built from the tracker data.'}</h1>
          <p class="hero-copy">${isPromptMode ? 'This view was generated directly from the prompt in the URL. The backend interpreted tracker data and the page rendered the resulting chart spec.' : 'Ask for charts only when you want them. The backend requests fixed chart-spec JSON, then the page renders those specs with existing code.'}</p>
          <div class="chart-action-block">
            <label class="chart-request-box">
              <span>Describe the chart you want</span>
              <textarea class="chart-request-input" placeholder="Example: Show a line chart for homelessness trend and a bar chart comparing public safety indicators.">${escapeHtml(chartRequestText)}</textarea>
            </label>
            <button type="button" class="chart-generate-button" ${isGenerating ? 'disabled' : ''}>${isGenerating ? 'Generating…' : 'Generate charts'}</button>
            <p class="chart-action-warning">this number of charts may be limited in the future;</p>
            ${generationError ? `<p class="chart-action-error">${escapeHtml(generationError)}</p>` : ''}
          </div>
          <div class="hero-tags">
            <span>${icon.refresh} Updated ${new Date(data.subject.lastUpdated).toLocaleDateString()}</span>
            <span>${chartCount} chart types visible</span>
            <span>${data.metrics.filter((metric) => metric.observations?.length).length} metrics with observations</span>
          </div>
        </div>
        <div class="hero-card">
          <div class="metric-icon">${icon.chart}</div>
          <strong>${chartCount}</strong>
          <p>Default charts come from saved tracker data, and AI requests return structured specs instead of UI code.</p>
        </div>
      </div>
    </header>
    ${isCleanPromptView ? chartsSection : (isPromptMode ? `${chartsSection}${summarySection}` : `${summarySection}${chartsSection}`)}
  `;

  document.querySelector('.chart-generate-button')?.addEventListener('click', generateCharts);
  document.querySelector('.chart-request-input')?.addEventListener('input', (event) => {
    chartRequestText = event.target.value;
  });
}

function renderGeneratedChart(chart) {
  if (chart.chartType === 'line') return renderLineChart(chart);
  if (chart.chartType === 'bar') return renderBarChart(chart);
  if (chart.chartType === 'donut') return renderDonutChart(chart);
  return renderScorecard(chart);
}

function renderLineChart(chart) {
  const metricContext = resolvePrimaryMetric(chart);
  const valueLabel = chart.valueLabel || metricContext?.label || 'Value';
  const xAxisLabel = chart.xAxisLabel || 'Observation date';
  const yAxisTitleClass = valueLabel.length > 34 ? 'chart-axis-title chart-axis-title-compact' : 'chart-axis-title';
  const plot = { left: 130, right: 54, top: 36, bottom: 118, width: 994, height: 396 };
  const orderedPoints = sortLinePoints(chart.data.points);
  const max = Math.max(...orderedPoints.map((point) => point.value));
  const min = Math.min(...orderedPoints.map((point) => point.value));
  const range = Math.max(max - min, 1);
  const scaledPoints = orderedPoints.map((point, index) => {
    const x = plot.left + (index / Math.max(orderedPoints.length - 1, 1)) * plot.width;
    const y = plot.top + ((max - point.value) / range) * plot.height;
    return { ...point, x, y };
  });
  const linePoints = scaledPoints.map((point) => `${point.x},${point.y}`).join(' ');
  const yTicks = buildNumericTicks(min, max, 5).map((value, index, values) => ({
    key: `y-${index}`,
    value,
    y: plot.top + ((values[0] - value) / Math.max(values[0] - values.at(-1), 1)) * plot.height,
  }));
  const xLabelPoints = chooseXAxisLabels(scaledPoints);
  const labels = [scaledPoints[0], scaledPoints[scaledPoints.length - 1]]
    .filter(Boolean)
    .map((point) => `<span>${formatShortDate(point.label)}: ${formatValue(point.value)}</span>`)
    .join('');
  const rangeLabel = orderedPoints.length > 1
    ? `${formatShortDate(orderedPoints[0].label)} to ${formatShortDate(orderedPoints[orderedPoints.length - 1].label)}`
    : formatShortDate(orderedPoints[0]?.label || '');

  return `<article class="chart-card chart-card-wide">
    <div class="metric-chart-head">
      <div><span>${pretty(chart.chartType)} chart</span><h3>${chart.title}</h3></div>
      <strong>${scaledPoints.length}</strong>
    </div>
    <p>${chart.rationale}</p>
    <svg class="real-chart-svg line-chart-svg" viewBox="0 0 1200 620" role="img" aria-label="${chart.title}">
      <text x="${plot.left + (plot.width / 2)}" y="592" text-anchor="middle" class="chart-axis-title">${escapeHtml(xAxisLabel)}</text>
      <text x="38" y="${plot.top + (plot.height / 2)}" text-anchor="middle" class="${yAxisTitleClass}" transform="rotate(-90 38 ${plot.top + (plot.height / 2)})">${escapeHtml(valueLabel)}</text>
      ${yTicks.map((tick) => `<g>
        <line x1="${plot.left}" y1="${tick.y}" x2="${plot.left + plot.width}" y2="${tick.y}" class="chart-gridline"></line>
        <line x1="${plot.left - 12}" y1="${tick.y}" x2="${plot.left}" y2="${tick.y}" class="chart-tick"></line>
        <text x="${plot.left - 18}" y="${tick.y + 6}" text-anchor="end" class="chart-axis-label">${formatChartValue(tick.value, chart)}</text>
      </g>`).join('')}
      <line x1="${plot.left}" y1="${plot.top + plot.height}" x2="${plot.left + plot.width}" y2="${plot.top + plot.height}" class="chart-axis chart-axis-strong"></line>
      <line x1="${plot.left}" y1="${plot.top}" x2="${plot.left}" y2="${plot.top + plot.height}" class="chart-axis chart-axis-strong"></line>
      ${xLabelPoints.map((point) => `<g>
        <line x1="${point.x}" y1="${plot.top + plot.height}" x2="${point.x}" y2="${plot.top + plot.height + 10}" class="chart-tick"></line>
        <text x="${point.x}" y="${plot.top + plot.height + 34}" text-anchor="middle" class="chart-axis-label">${escapeHtml(formatShortDate(point.label))}</text>
      </g>`).join('')}
      <polyline points="${linePoints}" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"></polyline>
      ${scaledPoints.map((point, index) => `<circle cx="${point.x}" cy="${point.y}" r="${index === scaledPoints.length - 1 ? 7.5 : 5.5}"></circle>`).join('')}
    </svg>
    <div class="chart-stats">
      ${metricContext?.label ? `<span>${escapeHtml(metricContext.label)}</span>` : ''}
      ${metricContext?.source ? `<span>${escapeHtml(metricContext.source)}</span>` : ''}
      ${rangeLabel ? `<span>${escapeHtml(rangeLabel)}</span>` : ''}
      <span>${formatCountLabel(orderedPoints.length, chart.countLabelSingular || 'observation')}</span>
      ${labels}
    </div>
  </article>`;
}

function renderBarChart(chart) {
  const metricContext = resolvePrimaryMetric(chart);
  const valueLabel = chart.valueLabel || metricContext?.label || 'Value';
  const metricLabelChip = metricContext?.label && metricContext.label !== valueLabel
    ? `<span>${escapeHtml(metricContext.label)}</span>`
    : '';
  const xAxisLabel = chart.xAxisLabel || 'Observation period';
  const yAxisTitleClass = valueLabel.length > 32 ? 'chart-axis-title chart-axis-title-compact' : 'chart-axis-title';
  const hasDenseTimeSeries = chart.data.bars.length > 8;
  const plot = hasDenseTimeSeries
    ? { left: 132, right: 54, top: 36, bottom: 118, width: 994, height: 392 }
    : { left: 126, right: 54, top: 36, bottom: 110, width: 960, height: 380 };
  const maxValue = Math.max(...chart.data.bars.map((bar) => bar.value), 0);
  const yTicks = buildNumericTicks(0, maxValue, 5).map((value, index, values) => ({
    value,
    y: plot.top + ((values[0] - value) / Math.max(values[0] - values.at(-1), 1)) * plot.height,
  }));
  const slotWidth = plot.width / Math.max(chart.data.bars.length, 1);
  const barWidth = Math.max(slotWidth - 14, hasDenseTimeSeries ? 36 : 52);
  const bars = chart.data.bars.map((bar, index) => {
    const x = plot.left + (index * slotWidth) + ((slotWidth - barWidth) / 2);
    const height = maxValue ? (bar.value / maxValue) * plot.height : 0;
    const y = plot.top + plot.height - height;
    return { ...bar, x, y, width: barWidth, height };
  });
  const xLabels = chooseBarXAxisLabels(bars);
  const rangeLabel = buildCategoryRangeLabel(chart.data.bars.map((bar) => formatCategoryLabel(bar.label)));
  const chartClass = hasDenseTimeSeries ? 'chart-card chart-card-wide' : 'chart-card';

  return `<article class="${chartClass}">
    <div class="metric-chart-head">
      <div><span>${pretty(chart.chartType)} chart</span><h3>${chart.title}</h3></div>
      <strong>${chart.data.bars.length}</strong>
    </div>
    <p>${chart.rationale}</p>
    <svg class="real-chart-svg bar-chart-svg" viewBox="0 0 1200 620" role="img" aria-label="${chart.title}">
      <text x="${plot.left + (plot.width / 2)}" y="592" text-anchor="middle" class="chart-axis-title">${escapeHtml(xAxisLabel)}</text>
      <text x="40" y="${plot.top + (plot.height / 2)}" text-anchor="middle" class="${yAxisTitleClass}" transform="rotate(-90 40 ${plot.top + (plot.height / 2)})">${escapeHtml(valueLabel)}</text>
      ${yTicks.map((tick) => `<g>
        <line x1="${plot.left}" y1="${tick.y}" x2="${plot.left + plot.width}" y2="${tick.y}" class="chart-gridline"></line>
        <line x1="${plot.left - 12}" y1="${tick.y}" x2="${plot.left}" y2="${tick.y}" class="chart-tick"></line>
        <text x="${plot.left - 18}" y="${tick.y + 6}" text-anchor="end" class="chart-axis-label">${formatBarValue(tick.value, chart)}</text>
      </g>`).join('')}
      <line x1="${plot.left}" y1="${plot.top + plot.height}" x2="${plot.left + plot.width}" y2="${plot.top + plot.height}" class="chart-axis chart-axis-strong"></line>
      <line x1="${plot.left}" y1="${plot.top}" x2="${plot.left}" y2="${plot.top + plot.height}" class="chart-axis chart-axis-strong"></line>
      ${bars.map((bar) => `<rect x="${bar.x}" y="${bar.y}" width="${bar.width}" height="${Math.max(bar.height, 2)}" rx="8" class="chart-bar"></rect>`).join('')}
      ${xLabels.map((bar) => `<g>
        <line x1="${bar.x + (bar.width / 2)}" y1="${plot.top + plot.height}" x2="${bar.x + (bar.width / 2)}" y2="${plot.top + plot.height + 10}" class="chart-tick"></line>
        <text x="${bar.x + (bar.width / 2)}" y="${plot.top + plot.height + 34}" text-anchor="middle" class="chart-axis-label">${escapeHtml(formatCategoryLabel(bar.label))}</text>
      </g>`).join('')}
    </svg>
    <div class="chart-stats">
      <span>${escapeHtml(valueLabel)}</span>
      ${metricLabelChip}
      ${metricContext?.source ? `<span>${escapeHtml(metricContext.source)}</span>` : ''}
      ${rangeLabel ? `<span>${escapeHtml(rangeLabel)}</span>` : ''}
      <span>${formatCountLabel(bars.length, chart.countLabelSingular || 'bar')}</span>
      <span>Peak: ${formatBarValue(maxValue, chart)}</span>
    </div>
  </article>`;
}

function renderDonutChart(chart) {
  const metricContext = resolvePrimaryMetric(chart);
  const valueLabel = chart.valueLabel || 'Count';
  const total = chart.data.slices.reduce((sum, slice) => sum + slice.value, 0);
  const colors = ['#2d546e', '#6f8aa0', '#c0874d', '#c95f4a', '#9ea8b0'];
  let startAngle = 0;
  const slices = chart.data.slices.map((slice, index) => {
    const portion = total ? slice.value / total : 0;
    const endAngle = startAngle + (portion * Math.PI * 2);
    const path = donutSlicePath(50, 50, 38, 24, startAngle, endAngle);
    startAngle = endAngle;
    return {
      ...slice,
      color: colors[index % colors.length],
      path,
      share: total ? Math.round(portion * 100) : 0,
    };
  });

  return `<article class="chart-card">
    <div class="metric-chart-head">
      <div><span>${pretty(chart.chartType)} chart</span><h3>${chart.title}</h3></div>
      <strong>${total}</strong>
    </div>
    <p>${chart.rationale}</p>
    <div class="donut-layout">
      <svg class="donut-chart-svg" viewBox="0 0 100 100" role="img" aria-label="${chart.title}">
        ${slices.map((slice) => `<path d="${slice.path}" fill="${slice.color}"></path>`).join('')}
        <circle cx="50" cy="50" r="18" fill="#ffffff"></circle>
        <text x="50" y="47" text-anchor="middle" class="donut-number">${total}</text>
        <text x="50" y="57" text-anchor="middle" class="donut-label">total</text>
      </svg>
      <div class="donut-legend">
        ${slices.map((slice) => `<div class="legend-row"><span class="legend-swatch" style="background:${slice.color}"></span><strong>${escapeHtml(slice.label)}</strong><em>${formatValue(slice.value)} (${slice.share}%)</em></div>`).join('')}
      </div>
    </div>
    <div class="chart-stats">
      <span>${escapeHtml(valueLabel)}</span>
      <span>Share of total</span>
      ${metricContext?.label ? `<span>${escapeHtml(metricContext.label)}</span>` : ''}
      ${chart.sourceTitles?.length ? `<span>${escapeHtml(chart.sourceTitles[0])}</span>` : ''}
      <span>${formatCountLabel(slices.length, chart.countLabelSingular || 'category')}</span>
      <span>Total: ${formatValue(total)}</span>
    </div>
  </article>`;
}

function renderScorecard(chart) {
  const metricContext = resolvePrimaryMetric(chart);
  return `<article class="chart-card">
    <div class="metric-chart-head">
      <div><span>${pretty(chart.chartType)} chart</span><h3>${chart.title}</h3></div>
      <strong>${chart.data.items.length}</strong>
    </div>
    <p>${chart.rationale}</p>
    <div class="event-list">
      ${chart.data.items.map((item) => `<div><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(item.value)}</strong>${item.context ? `<small class="scorecard-context">${escapeHtml(item.context)}</small>` : ''}</div>`).join('')}
    </div>
    <div class="chart-stats">
      ${metricContext?.label ? `<span>${escapeHtml(metricContext.label)}</span>` : ''}
      ${metricContext?.source ? `<span>${escapeHtml(metricContext.source)}</span>` : ''}
      <span>${formatCountLabel(chart.data.items.length, chart.countLabelSingular || 'item')}</span>
    </div>
  </article>`;
}

async function generateCharts() {
  const requestText = chartRequestText.trim();
  const isPromptRequest = Boolean(requestText);
  isGenerating = true;
  generationError = '';
  if (isPromptRequest) hasGeneratedPromptCharts = false;
  render();
  try {
    syncPromptUrl(requestText);
    const response = await fetch('/api/generate-charts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ chartRequest: requestText, trackerSlug: trackerContext.tracker.slug }),
    });
    const payload = await response.json();
    if (!response.ok) throw new Error(payload.error || `Request failed with ${response.status}`);
    generatedCharts = Array.isArray(payload.charts) && payload.charts.length ? payload.charts : defaultCharts;
    hasGeneratedPromptCharts = isPromptRequest;
  } catch (error) {
    generationError = error.message;
    generatedCharts = defaultCharts;
  } finally {
    isGenerating = false;
    render();
  }
}

function readPromptFromUrl() {
  const url = new URL(window.location.href);
  return url.searchParams.get('prompt')?.trim() || '';
}

function readViewModeFromUrl() {
  const url = new URL(window.location.href);
  return url.searchParams.get('view')?.trim() || '';
}

function syncPromptUrl(promptText) {
  const url = new URL(window.location.href);
  if (promptText) {
    url.searchParams.set('prompt', promptText);
    if (!url.searchParams.get('view')) url.searchParams.set('view', 'clean');
  } else {
    url.searchParams.delete('prompt');
    url.searchParams.delete('view');
  }
  window.history.replaceState({}, '', `${url.pathname}${url.search}${url.hash}`);
}

function pretty(value) {
  return value.replaceAll('_', ' ');
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[character]));
}

function formatShortDate(value) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString(undefined, { month: 'short', year: 'numeric' });
}

function formatValue(value) {
  return Number.isFinite(value) ? value.toLocaleString() : String(value);
}

function formatAxisNumber(value) {
  return new Intl.NumberFormat(undefined, {
    notation: Math.abs(value) >= 10000 ? 'compact' : 'standard',
    maximumFractionDigits: Math.abs(value) >= 100 ? 0 : 1,
  }).format(value);
}

function formatChartValue(value, chart) {
  if (chart.valueFormat === 'percent') return `${formatAxisNumber(value)}%`;
  return formatAxisNumber(value);
}

function formatBarValue(value, chart) {
  return formatChartValue(value, chart);
}

function formatCountLabel(count, singular) {
  return `${count} ${count === 1 ? singular : pluralizeLabel(singular)}`;
}

function pluralizeLabel(label) {
  if (/(s|x|z|ch|sh)$/i.test(label)) return `${label}es`;
  if (label.endsWith('y') && !/[aeiou]y$/i.test(label)) return `${label.slice(0, -1)}ies`;
  return `${label}s`;
}

function resolvePrimaryMetric(chart) {
  const metricId = chart.metricIds?.[0];
  if (!metricId || !trackerData?.metrics) return null;
  return trackerData.metrics.find((metric) => metric.id === metricId) || null;
}

function buildCategoryRangeLabel(labels) {
  if (!labels.length) return '';
  if (labels.length === 1) return labels[0];
  return `${labels[0]} to ${labels[labels.length - 1]}`;
}

function formatCategoryLabel(label) {
  const monthlyMatch = String(label).match(/^(\d{4})-(\d{2})$/);
  if (monthlyMatch) {
    const date = new Date(`${monthlyMatch[1]}-${monthlyMatch[2]}-01T00:00:00`);
    return Number.isNaN(date.getTime())
      ? label
      : date.toLocaleDateString(undefined, { month: 'short', year: 'numeric' });
  }
  return label;
}

function chooseBarXAxisLabels(bars) {
  if (bars.length <= 6) return bars;
  return chooseEvenlySpacedItems(bars, Math.min(6, bars.length));
}

function sortLinePoints(points) {
  return [...points].sort((left, right) => {
    const leftDate = Date.parse(left.label);
    const rightDate = Date.parse(right.label);
    if (Number.isNaN(leftDate) || Number.isNaN(rightDate)) return 0;
    return leftDate - rightDate;
  });
}

function chooseXAxisLabels(points) {
  if (points.length <= 6) return points;
  return chooseEvenlySpacedItems(points, Math.min(6, points.length));
}

function chooseEvenlySpacedItems(items, count) {
  if (items.length <= count) return items;
  const lastIndex = items.length - 1;
  const selected = [];
  for (let index = 0; index < count; index += 1) {
    const itemIndex = Math.round((index / (count - 1)) * lastIndex);
    selected.push(items[itemIndex]);
  }
  return selected.filter((item, index, list) => list.findIndex((candidate) => candidate === item) === index);
}

function buildNumericTicks(min, max, desiredCount = 5) {
  if (!Number.isFinite(min) || !Number.isFinite(max)) return [0];
  if (min === max) {
    return Array.from({ length: desiredCount }, (_, index) => {
      const offset = (desiredCount - 1 - index) * Math.max(Math.abs(max) * 0.05, 1);
      return Number((max - offset).toFixed(6));
    });
  }

  const span = max - min;
  const roughStep = span / Math.max(desiredCount - 1, 1);
  const magnitude = 10 ** Math.floor(Math.log10(Math.max(roughStep, 1)));
  const normalized = roughStep / magnitude;
  const niceFactor = normalized <= 1 ? 1 : normalized <= 2 ? 2 : normalized <= 2.5 ? 2.5 : normalized <= 5 ? 5 : 10;
  const step = niceFactor * magnitude;
  const top = Math.ceil(max / step) * step;
  const bottom = Math.floor(min / step) * step;
  const ticks = [];

  for (let value = top; value >= bottom - (step / 2); value -= step) {
    ticks.push(Number(value.toFixed(6)));
  }

  while (ticks.length < desiredCount) {
    ticks.push(Number((ticks.at(-1) - step).toFixed(6)));
  }

  return ticks;
}

function polarToCartesian(centerX, centerY, radius, angle) {
  return {
    x: centerX + (radius * Math.cos(angle - (Math.PI / 2))),
    y: centerY + (radius * Math.sin(angle - (Math.PI / 2))),
  };
}

function donutSlicePath(cx, cy, outerRadius, innerRadius, startAngle, endAngle) {
  const outerStart = polarToCartesian(cx, cy, outerRadius, startAngle);
  const outerEnd = polarToCartesian(cx, cy, outerRadius, endAngle);
  const innerEnd = polarToCartesian(cx, cy, innerRadius, endAngle);
  const innerStart = polarToCartesian(cx, cy, innerRadius, startAngle);
  const largeArcFlag = endAngle - startAngle > Math.PI ? 1 : 0;

  return [
    `M ${outerStart.x} ${outerStart.y}`,
    `A ${outerRadius} ${outerRadius} 0 ${largeArcFlag} 1 ${outerEnd.x} ${outerEnd.y}`,
    `L ${innerEnd.x} ${innerEnd.y}`,
    `A ${innerRadius} ${innerRadius} 0 ${largeArcFlag} 0 ${innerStart.x} ${innerStart.y}`,
    'Z',
  ].join(' ');
}

boot().catch((error) => {
  document.getElementById('root').textContent = `Unable to load charts page: ${error.message}`;
});
